name: Update data from https://orc.org
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/checkout@v4
      - run: make json
      - run: make site
      - id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update data from https://orc.org on ${{ env.date }}
          body: Automated update of data from https://orc.org
          commit-message: Update data from https://orc.org on ${{ env.date }}
          branch: update-data-${{ env.date }}
          reviewers: jieter
